spring.application.name=spring-boot-starter-kit
spring.threads.virtual.enabled=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

jwt.whitelist=/v3/api-docs/**,/swagger-ui/**,/api/v1/auth/**
jwt.secretKey=aebfd964e9d6ad56ddd1b186d971362ef41bda8bec52ed724ac788f17434b317